/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jncjcoder.aula3;

/**
 *
 * @author RYZEN
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClick = new java.awt.Button();
        lblResultado = new java.awt.Label();
        btnMouse = new java.awt.Button();
        btnFoco = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnClick.setLabel("Click");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        getContentPane().add(btnClick);
        btnClick.setBounds(20, 20, 42, 24);

        lblResultado.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblResultado.setText("Resultado");
        getContentPane().add(lblResultado);
        lblResultado.setBounds(20, 180, 360, 110);

        btnMouse.setLabel("Ao passar o mouse");
        btnMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseMouseExited(evt);
            }
        });
        getContentPane().add(btnMouse);
        btnMouse.setBounds(90, 10, 190, 40);

        btnFoco.setLabel("Foco");
        btnFoco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnFocoFocusGained(evt);
            }
        });
        getContentPane().add(btnFoco);
        btnFoco.setBounds(310, 20, 55, 24);

        setBounds(0, 0, 414, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        lblResultado.setText("Click do Botão");
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnMouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMouseEntered
        // TODO add your handling code here:
        lblResultado.setText("O Mouse entrou na área do botão");
    }//GEN-LAST:event_btnMouseMouseEntered

    private void btnMouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseMouseExited
        // TODO add your handling code here:
        lblResultado.setText("O Mouse saiu da área do botão");
    }//GEN-LAST:event_btnMouseMouseExited

    private void btnFocoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnFocoFocusGained
        // TODO add your handling code here:
        lblResultado.setText("O botão recebeu o foco");
    }//GEN-LAST:event_btnFocoFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnClick;
    private java.awt.Button btnFoco;
    private java.awt.Button btnMouse;
    private java.awt.Label lblResultado;
    // End of variables declaration//GEN-END:variables
}
